[package]
name = "macros"
version = "0.1.0"
description = "Macro library used by the project"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
emojis = "0.6.1"
quote = "1.0.33"
rand = "0.8.5"
syn = "2.0.37"

[dev-dependencies]
pretty_assertions = "1.4.0"
