[package]
name = "binge_at_home"
version = "0.1.0"

[workspace]
members = ["api", "entity", "core"]

[workspace.package]
edition = "2021"
authors = ["Attila Szőke"]
readme = "./README.md"
repository = "https://github.com/szattila98/binge_at_home"
license = "MIT"

[dependencies]
