ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = []
post_bump_hooks = [
    "git push",
    "git push origin {{version}}"
]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "binge_at_home"
owner = "szattila98"
authors = [
    { username = "szattila98", signature = "Attila Szőke" },
    { username = "doleance", signature = "doleance" },
]

[bump_profiles]

[packages]
client = { path = "client", pre_bump_hooks = [ "npm version {{version}}", "npm run build" ] }
server = { path = "server", pre_bump_hooks = [ "cargo set-version {{version}}", "cargo build --release" ] }

[git_hooks.pre-push]
script = """#!/bin/sh
set -e
cog check
"""
