ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = []
post_bump_hooks = ["git push", "git push origin --tags"]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "binge_at_home"
owner = "szattila98"
authors = [
    { username = "szattila98", signature = "Attila Szőke" },
    { username = "doleance", signature = "doleance" },
    { username = "CsalaPeter", signature = "Péter Csala" }
]

[bump_profiles]

[packages]
server = { path = "server", pre_bump_hooks = ["cargo set-version -p binge-at-home {{version}}"] }
macros = { path = "server/macros", pre_bump_hooks = ["cargo set-version -p macros {{version}}"], public_api = false }

[git_hooks.pre-push]
script = """#!/bin/sh
set -e
cog check
"""
