version: '3.9'

services:
  database:
    container_name: binge-at-home-database
    image: postgres:16
    environment:
      - POSTGRES_DB=binge-at-home
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./dev/postgres-data:/var/lib/postgresql/data

  server:
    container_name: binge-at-home-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dev/store:/app/store
    depends_on:
      database:
        condition: service_healthy
