version: '3.9'

services:
  database:
    container_name: binge-at-home-database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: binge-at-home-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  client:
    container_name: binge-at-home-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - server
