[package]
name = "binge-at-home"
version = "0.1.0"
description = "Self-hosted video streaming application"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "binge-at-home"

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["macros"] }
axum-extra = { version = "0.7.7", features = ["typed-routing"] }
confique = { version = "0.2.4", default-features = false, features = ["yaml"] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "macros",
    "migrate",
] }
tokio = { version = "1.29.1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.3", features = [
    "util",
    "compression-gzip",
    "cors",
    "limit",
    "trace",
    "request-id",
    "timeout",
    "validate-request",
    "catch-panic",
] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["registry"] }
utoipa = "3.4.3"
utoipa-swagger-ui = { version = "3.1.4", features = ["axum"] }
