name: Conventional commits

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check conventional commit compliance
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3.4
